### ISSUE TITLE
CSS style sheet branding  

### ISSUE THREAD

**Issue by navinw** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#10]
CSS style sheet branding

**Comment by uiguru** [comment]
Please see detail below of a suggested theme for Mubadala.  Please note, the font stack refers to variants of the Avenir font (as per their style guidelines), but this will only work if the web fonts are correctly referenced / hosted. If the client is not able to work with us for a solution to rendering a correctly licenced font then the UI will render in Arial / Helvetica. 

WHITE LOGO:
![mubadala-logo](https://cloud.githubusercontent.com/assets/10029833/20796234/256105e8-b7cd-11e6-852e-2207e5bc8e36.png)

Mockup using these colours:
![mubadala-mockup](https://cloud.githubusercontent.com/assets/10029833/20796246/396214e2-b7cd-11e6-965b-f7c72310412e.jpg)


THEME JSON:

{
      "id": "mubadala",
                "primary": "#005a8C",       
                "secondary": "#55c5e9",    
                "backgrounds": "#FFFFFF",
                "foregrounds": "#575a5d",      
                "fonts": "Avenir-Medium,"Avenir LT W01 65 Medium",Avenir,Helvetica,Arial,sans-serif",
                "pageBackground":"#d7d3c8",
                "positive":"#1c87c9",
                "balanced":"#74b343",
                "energized":"#f2a61e",
                "assertive":"#e12028"
}

**Comment by uiguru** [comment]
The Mubadala favicon can be downloaded from the following URL:
https://www.mubadala.com/sites/all/themes/whippy_new/favicon.ico

@SowjanyaDudipalla @JaganMohan27  @navinw - please note that today Mubadala have raised a new support ticket requesting different brands per business group. So this is sure to change the theming requirements in due course.

**Comment by SowjanyaDudipalla** [comment]
Software Patch v002806 applied successfully.updated favicon, taken from above specified URL..

**Comment by SowjanyaDudipalla** [comment]
Home page after updating favicon ,stylesheet .

![advert4](https://cloud.githubusercontent.com/assets/21194907/21448848/125393c0-c90d-11e6-974c-310424025d77.PNG)

**Comment by uiguru** [comment]
Thanks for the screenshot @SowjanyaDudipalla - theme, icon and favicon all looks good.  The new header image is much better now too - although the middle part actually looks like an aerial photograph of my head :-)
