### ISSUE TITLE
HR Landing page

### ISSUE THREAD

**Issue by navinw** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#11]
HR Landing page containing:

o	‘Advert’ or image with message and link
o	1 RSS Feed of Mubadala’s choice
o	1 embedded Twitter feed of Mubadala’s choice
o	‘Quick Link’ menu with up to 6 links to Applaud screens, Oracle screens or other intranet sites
o	Mini-worklist
o	Link to View Payslip (optional for Payroll customers)
o	Note: to accelerate deployment and avoid time taken up with requirement gathering, Applaud will use template assets for the following components:
	Advert (we can take an image from Mubadala website
	Twitter feed (we can use Mubadala’s official Twitter feed)
	RSS Feed (we can use a publicly available RSS feed as a template)

**Comment by SowjanyaDudipalla** [comment]
Quick Link’ menu setup upto 4links is completed.Need more specifications on two specified links.
Mini worklist setup is completed.
Removed Twitter feed of Mubadala’s choice as per requirement.

**Comment by SowjanyaDudipalla** [comment]
Specifications need for Quick Links are : 

Quick Links are:

1-      Salary Certificate -Need exact function.

2-      Absence Management-This is Done  👍 
 
3-      Loan Management -This is menu, they need to specify any function inside that menu.

4-      HC Helpdesk -Need more specification.Specific Function.I didn't find any Help desk function .

**Comment by SowjanyaDudipalla** [comment]
Link to View Latest Payslip is done👍 .Previously payslip data format  was wrong. 
For this,updated Fast Formula,By adding required Template in Fast Formula conditioning the Legislation Code 'AE' customer's code.

**Comment by karthmoh** [comment]
Link to be removed from Advert image.

**Comment by karthmoh** [comment]
Advert image attached.
![employee center_main screen](https://cloud.githubusercontent.com/assets/12637571/21095493/a3763afe-c081-11e6-81c2-bc9fb80ccaa3.jpg)

**Comment by SowjanyaDudipalla** [comment]
Updated Advert image and removed link from the image as per requirement.

![advert](https://cloud.githubusercontent.com/assets/21194907/21096447/ef997f5a-c085-11e6-9f72-9c145af4cda5.PNG)

**Comment by SowjanyaDudipalla** [comment]
Updated New Advert image, which is having required pixels(1200X400) .

![advert3](https://cloud.githubusercontent.com/assets/21194907/21448504/72bf8cae-c909-11e6-8907-ed562869a435.PNG)
