### ISSUE TITLE
Push Notifications for worklist approvals

### ISSUE THREAD

**Issue by navinw** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#12]
Push Notifications for worklist approvals

**Comment by asinghmdcbms** [comment]
Dear Hari/Navin,

Our dba wanted to have few clarifications regarding configuring push notifications as per attached document  on our pre-production environment.

Can we please have a quick call today to close this. 



Basically we needed clarifications on below points in document 


1.	Import the CA certificate provided by Applaud as below

$ orapki wallet add -wallet . -trusted_cert -cert <certificate>.crt -pwd <password>


DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(
          acl           => l_filename
        , host          => '*.applaudcloud.com'
        , lower_port    => *
    );


Also, can you please review this :-

=============================
Hi Amit,

Please confirm with applaud team whether below destination is enough for push notifications functionality and also is destination hostname/IP is same for both P1 and PP1?

Test instance
Source:                  (TEST Database )
PP1 : ALBSL1ORCODA001 - 10.23.89.36
PP1 : ALBSL1ORCODA002  - 10.23.89.37
Destination :      acs.applaudsolutions.com - 52.26.112.138 

Port : 8111


Production : 
Source:                 (Production database)
P1 : ALBSL1ODAPRD001 - 10.21.89.36
P1 : ALBSL1ODAPRD002 - 10.21.89.37
Destination         : acs.applaudsolutions.com - 52.26.112.138 

Port : 8111  

And also as per the document we require the certificate from applaud to import into our database server.


=============================
[How to enable Push Notifications.docx](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/682925/How.to.enable.Push.Notifications.docx)

**Comment by duncancasemore** [comment]
Hi

Both applaudsolutions and applaudcloud are needed to ensure push works now and in the future.

Documentation including certificates is available here:
http://docs.applaudsolutions.com/push-notifications

Duncan

**Comment by asinghmdcbms** [comment]
hi..

We had call with team sometime back today and we were told that we only need to have database connectivity to acs.applaudsolutions.com:8111 for now.

Connectivity to *.applaudcloud.com:* is something which would be needed in future and below is of no relevance for now.

   DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(
          acl           => l_filename
        , host          => '*.applaudcloud.com'
        , lower_port    => *
    );

Based on the last response can you please confirm if connectivity for *.applaudcloud.com is needed even now ? And what does 'lower_port    => *' mean; does it mean open for all the ports for host *.applaudcloud.com ?

**Comment by duncancasemore** [comment]
Our services, including push, will be using both applaudsolutions.com and applaudcloud.com.  Today it's just using applaudsolutions.com but you will need to plan to have both, otherwise it will break at a future date.
