### ISSUE TITLE
Logged in user menu context - Banner with contact details are missing

### ISSUE THREAD

**Issue by karthmoh** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#17]
Looks like some issue around the grants for the permission - XXAS_SHOW_PERSON_MENU_CTX

**Comment by SowjanyaDudipalla** [comment]
Created Grant with XXX Applaud Employee Self Service Role for XXAS_SHOW_PERSON_MENU_CTX Permission set .Banner is coming up 👍
