### ISSUE TITLE
Setup New Charts as requested

### ISSUE THREAD

**Issue by hgajula-applaud** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#18]
Create New Charts as per Hedaya's request . 
Need to discuss more with the team.

**Comment by Yasotharan** [comment]
duplicate of #13

**Comment by hgajula-applaud** [comment]
Yaso, we need to discuss with Mubadala team to get more details of what other charts needs to be built which is covered out of SOW.

**Comment by hgajula-applaud** [comment]
No further requirements requested.
