### ISSUE TITLE
Build Mobile apps

### ISSUE THREAD

**Issue by hgajula-applaud** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#25]
Build custom apps by embedding the url provided.

**Comment by hgajula-applaud** [comment]
details will be provided soon.

**Comment by asinghmdcbms** [comment]
We would be needing 2 set of apps, one for our test instance and one for production.

Url for test :  http://crp2.pp.mdcbms.ae:8010/OA_HTML/AppsLogin
Url for prod : https://mpower.corp.services.mdc/OA_HTML/AppsLogin

**Comment by asinghmdcbms** [comment]
Hi Amit,

I will get this done at the earliest.

Thanks
Hari

On 22 December 2016 at 16:05, Amit Kumar Awadhesh Kumar Singh (MDCBMS) <asingh@mdcbms.ae> wrote:
Hi Hari,
 
Can we have this at the earliest.  The team is waiting to test the app in pre-production environment.
 
Thanks,
Amit Kumar Awadhesh Kumar Singh
m  +971 55 7000587    t  +971 2 413 0658

**Comment by karthmoh** [comment]
Hi Amit,

Please find the apps links :-

Prod :
ipa   :- https://www.dropbox.com/s/nzmiqya6b6r2xmf/MubadalaPro.ipa?dl=0
apk  :- https://www.dropbox.com/s/nydxwjize5q6nyp/MubadalaPro.apk?dl=0

Test :
ipa   :- https://www.dropbox.com/s/8jyg9v7120pk926/MubadalaTest.ipa?dl=0
apk  :- https://www.dropbox.com/s/56ot9ymx37xz2xv/MubadalaTest.apk?dl=0

Thanks,.

**Comment by asinghmdcbms** [comment]
hi,

We are getting below error when opening the native app which has url embedded :-


![image](https://cloud.githubusercontent.com/assets/23504285/21514956/7d178d44-cce4-11e6-89eb-d18982903ac8.png)

**Comment by satchava** [comment]
Please follow the below steps to enables SSO for applaud. 
http://support.applaudsolutions.com/hc/en-us/articles/205283637-Steps-to-enable-Oracle-Single-Sign-On-login-for-EmployeeCenter-Mobile

Recheck the issue after the above steps are completed.

**Comment by asinghmdcbms** [comment]
We were able to successfully push the apk/ipa files to users mobile devices using our mdm server.

However, issue was received when trying to open the app; this is being tracked via git #6 

Closing this git
