### ISSUE TITLE
Loan Management: Move all functions into a single page

### ISSUE THREAD

**Issue by karthmoh** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#26]

**Comment by SowjanyaDudipalla** [comment]
In Absence management menu,
We are having 6 pages 1.Absence Request 2.Per Diem 3. Business Trip Ticket Request 4.Training Trip Ticket Request 5.Leave Credit Request 6.Leave Encashment Request.
3,4,5,6 Pages are clubbed into single page.

**Comment by SowjanyaDudipalla** [comment]
Screenshot of modified page:

![clubbed](https://cloud.githubusercontent.com/assets/21194907/21479931/9b207088-cb7e-11e6-875c-40226d54318a.PNG)

**Comment by asinghmdcbms** [comment]
Its good that we are clubbing multiple functionalities on single page but can we first get a response on SR #31

**Comment by asinghmdcbms** [comment]
This is no more needed as it causes issues in mobile devices as per GIT#31. Closing.
