### ISSUE TITLE
Multiple Blocks on single page - Issue on Smart Phone 

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#30]
Applaud had clubbed Absence, Business Trip Ticket Request and Leave credit request on single page to show us the value addition of grouping multiple functions on a single page.

Below is how page looks on desktop vs on iPhone6 vs iPad.  The behavior looks good on Desktop and iPad. But not user-friendly at all on iPhone6.

My concern is :- 

If we are going to group multiple blocks in same page, it will be very tough to navigate on iPhone/Note 3. 
Like, for example, if we were planning to group all our 6 types of loans(car,housing,personal,topup,salary advance, loan history) on single page. How can we overcome this wrong behavior on iPhone? Also, what is your take on performance? Lets say if one of the loan SIT valueset query has performance issue, will it impact load of whole page, or will it  just effect rendering of specific SIT block ?

![smartphoneissue](https://cloud.githubusercontent.com/assets/23504285/21469805/d6af7f8e-ca81-11e6-96cb-2e5e723a440c.jpg)

**Comment by hgajula-applaud** [comment]
This is now re-configured . Please check now.

**Comment by asinghmdcbms** [comment]
We do not want to go for multiple blocks at the moment as navigation is not user friendly for mobile devices. Please revert it to the way it was originally.

**Comment by SowjanyaDudipalla** [comment]
Reverted all changes.Removed clubbed menus from Navigation menu.

**Comment by asinghmdcbms** [comment]
thanks
