### ISSUE TITLE
Peformance issue for worklist on home page 

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#31]
We want to track the issue related to performance issue related to load of notifications region.  Also, for sure we want to have the notifications region back to home page. Currently the home page looks very dull without the notifications region.

![homepage](https://cloud.githubusercontent.com/assets/23504285/21469821/a13a87d0-ca82-11e6-8a57-26ac46cbec0f.jpg)

Currently when we are pressing on the notifications tab, it is taking 8 seconds for first load.  Same behavior is there on chrome as well.  Hence, even having notification on separate tab is not helping at the moment.

From a functional perspective, all we are displaying for notifications is  subject,sender and time when notification was sent. This must not take 8seconds.  Let us know if any details are needed from our side to troubleshoot this issue.

**Comment by asinghmdcbms** [comment]
Hi Amit,

Sure we will work on this. But it would be better if you can log a github for this so that we don't get lost in emails.

Thanks
Hari

**Comment by karthmoh** [comment]
The latest software patch -  xxasemp-v002849 released includes the fix for the performance issues on worklist page.

**Comment by karthmoh** [comment]
Hi @asinghmdcbms, Could you please apply the latest patch in crp2 and test the performance.

**Comment by asinghmdcbms** [comment]
We have applied the latest patch on the crp2 instance. Run autoconfig and restarted services. The home page is taking 21 seconds to load.  Can you please let us know how much time it is taking for you ?

**Comment by asinghmdcbms** [comment]
Home page performance issue is being tracked via #32 

Closing this.
