### ISSUE TITLE
Error when applying HTML5 patch 

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#34]
Hi,

We are getting error when applying xxasemp-v002806.zip patch on our QA instance.

Logged below SR for it.

http://support.applaudsolutions.com/hc/en-us/requests/87741

Request you to please  help us resolve this at the earliest as we are planning to apply this patch in production on coming weekend.

**Comment by hgajula-applaud** [comment]
Thanks for logging. This will be resolved via SR .
