### ISSUE TITLE
Shading and Icon not appearing correctly in Internet Explorer

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#37]
The global header color shading and icon image is not displayed properly in Internet Explorer 11. Howver, this gets displayed correctly in chrome. Please note that IE is our official browser and is the only supported browser for all our corporate applications. Find below screenshot which explains issue clearly -

![image](https://cloud.githubusercontent.com/assets/23504285/21585404/cdb98c6e-d0d8-11e6-8234-cb6db519e4e7.png)

**Comment by JaganMohan27** [comment]
This is known issue. UI team is working on this.

**Comment by hgajula-applaud** [comment]
This is fixed. Can you test now ?
