### ISSUE TITLE
XXX_XXAS_EMP_VIEW_ABS_LOA_VIEW formula 

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#38]
hi,

Just wanted to check if there was any change done by applaud team in fast formula XXX_XXAS_EMP_VIEW_ABS_LOA_VIEW as part of html5 upgrade ? I can see some differences between our production copy and the one on crp2 instance. If no change was done by applaud then I will simply replace the formula definition from production.

Thanks

**Comment by JaganMohan27** [comment]
No Changes done XXX_XXAS_EMP_VIEW_ABS_LOA_VIEW  fast formula for html5 upgrade.

**Comment by asinghmdcbms** [comment]
Thanks for your response.
