### ISSUE TITLE
Error screen displayed after session time-out

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#39]
Once the user session time-outs we get the below error screen -

![image](https://cloud.githubusercontent.com/assets/23504285/21585680/c4784450-d0de-11e6-9176-d009a7158c5f.png)

The user should ideally be re-directed to login page after displaying an appropriate message.

**Comment by satchava** [comment]
found the root cause of the issue. To resolve this issue we need to run autoconfig and restart the services. 
Please let us know if we can run autoconfig on this instance.

**Comment by asinghmdcbms** [comment]
Let me ask our DBA to execute this activity

**Comment by asinghmdcbms** [comment]
We did run the autoconfig on apps-tier and restarted the services. But this doesn't look to resolve the issue. For testing this we had set profile 'ICX:Session Timeout' for user halammari (password : welcome@1234)  to 5 minutes,

If you feel the autoconfig was may be not done correctly by our dba, you may try from your end as well.

Please note the above error is also encountered in below two scenarios -

1) When we open below url directly in browser

http://crp2.pp.mdcbms.ae:8010/OA_HTML/a/#/person-home

2) When we launch the native app

**Comment by asinghmdcbms** [comment]
I tried again now(launching url http://crp2.pp.mdcbms.ae:8010/OA_HTML/a/#/person-home) and  instead of getting error page I got the login page. Just wanted to know if there was any fix done by Applaud to make it work ? (we had done autoconfig and middle-tier bounce in yesterday afternoon and after that we were still getting error)

However after login using Applaud screen, I was getting error that custom validation failed. Thereafter I set the below profile to null and after that I was able to login successfully using applaud login screen.

![image](https://cloud.githubusercontent.com/assets/23504285/21594678/dc975d86-d13e-11e6-9f64-87ddeaa499e9.png)


Please add the above step (setting above profile and rsa profile to no ) in the MD120. 
You may close this SR after noting above point in md120

Now below things are happening fine -

1) When we open url http://crp2.pp.mdcbms.ae:8010/OA_HTML/a/#/person-home login screen is presented to us and we are able to login successfully
2) After session timeout  login screen is presented to us and we are able to login successfully
3) Able to login using native app successfully on iPad
4) On another iPad I got error when launching though was able to login successfully. Will log separate SR for this
