### ISSUE TITLE
Menu changes in PROD

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#41]
hi,

A new menu(having single link) has been added in our production environment after we started with our html5 upgrade.  So this new menu is not there on the crp2 instance that applaud is using currently. When we migrate the applaud patch from crp2 to production how will this new menu be accommodated ?

find below the screenshot of new menu -

![image](https://cloud.githubusercontent.com/assets/23504285/21585845/950f24ce-d0e1-11e6-96f4-d8e5e2144e4d.png)

**Comment by SowjanyaDudipalla** [comment]
You can share us .LDT file of that particular menu.we will add to our manifest and deliver this new menu in new patch.

We will give some scripts for extracting .LDT file for that menu.

**Comment by asinghmdcbms** [comment]
Downloaded top level menu from PROD -

FNDLOAD apps/*** O Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct XXX_XXAS_EMP_REGISTERED_VIEWS.ldt MENU MENU_NAME="XXX_XXAS_EMP_REGISTERED_VIEWS"


This ldt has the new menu as well.
[XXX_XXAS_EMP_REGISTERED_VIEWS.zip](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/682904/XXX_XXAS_EMP_REGISTERED_VIEWS.zip)

**Comment by SowjanyaDudipalla** [comment]
@asinghmdcbms Thanks for the file.
But with this grants will be missing for that menu,I will share one script for grants can you please extract and share the file .

FNDLOAD apps/**** 0 Y DOWNLOAD $FND_TOP/patch/115/import/afsload.lct XXX_XXAS_BTR_GRANTS_MENU.ldt GRANT GNT_MENU_NAME='XXX_XXAS%'

please substitute "Permission set" code in GNT_MENU_NAME.

**Comment by asinghmdcbms** [comment]
Grant name is 'Grant BTR Links'

[XXX_XXAS_ESS.zip](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/684389/XXX_XXAS_ESS.zip)

**Comment by asinghmdcbms** [comment]
Please note above is download of XXX Applaud Employee Self-Service role

Below command we executed in prod -

FNDLOAD apps/supr3m3pas5 0 Y DOWNLOAD $FND_TOP/patch/115/import/afrole.lct XXX_XXAS_ESS.ldt WF_ROLE ROLE_NAME='UMX|XXX_XXAS_ESS'

**Comment by SowjanyaDudipalla** [comment]
Menu type is link,so we need details of XXX Registered Actions menu also.
can you please provide .LDT file for that menu too.
Thanks

**Comment by asinghmdcbms** [comment]
[XXX_XXAS_COM_REG_ACTIONS.zip](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/690505/XXX_XXAS_COM_REG_ACTIONS.zip)

**Comment by SowjanyaDudipalla** [comment]
Added this menu in 'XXX Applaud EmployeeCenter HTML Sub nav' will be delivered in patch.

**Comment by SowjanyaDudipalla** [comment]
Delivered in patch version 002911 .
