### ISSUE TITLE
Home links

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#42]
Our old global menu looked like below . Here 'Home' link meant Oracle home 'OA.jsp?OAFunc=OAHOMEPAGE'. While 'EmployeeCenter' link meant EmployeeCenter Home. 

![image](https://cloud.githubusercontent.com/assets/23504285/21586657/bdd26938-d0ec-11e6-9f2a-9913075149ab.png)

To avoid creating any confusion with the html5 upgrade and to continue using the same naming convention we need below changes in the existing screens

![image](https://cloud.githubusercontent.com/assets/23504285/21586587/2430b0c8-d0ec-11e6-8641-32a1e7abaf99.png)

**Comment by asinghmdcbms** [comment]
Please note we have earlier also requested to include oracle home as part of request #29

**Comment by SowjanyaDudipalla** [comment]
Removed label 'HOME ' from glance as per requirement .
![glance](https://cloud.githubusercontent.com/assets/21194907/21588278/4b14aa54-d10b-11e6-8b75-56dc2fefab30.PNG)

**Comment by asinghmdcbms** [comment]
Please note, after removing label 'HOME ' from At a glance page, the tab label is appearing as 'Untitled'. See below screenshot -
![image](https://cloud.githubusercontent.com/assets/23504285/21589145/476dc7e4-d108-11e6-9dc5-c7edb363e70c.png)
Looks page title is getting picked from label 'Home' that was removed. Can you please instead of removing label 'Home', name it as 'EmployeeCenter Home'

**Comment by SowjanyaDudipalla** [comment]
Updated as 'EmployeeCenter Home' .

![glance1](https://cloud.githubusercontent.com/assets/21194907/21589931/f9fb822a-d11c-11e6-8c10-7b2258eb616c.PNG)

**Comment by karthmoh** [comment]
The update of the Home link will be prioritized based on the discussion on #29 as this requires a software change.

**Comment by hgajula-applaud** [comment]
please see updates on #29
