### ISSUE TITLE
Branding not appearing for users for whom menu assigned recently.

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#44]
hi,

When assigning profile 'XXAS: Registered EmployeeCenter Views Menu' as  'XXX Applaud EmployeeCenter HTML Sub Nav' for new test users. eg. HALAMMARI/welcome@1234    .... the branding is not appearing correctly. However for existing users mhamza/welcome@1234; halhabsi/welcome@1234 the branding is appearing correctly.

![image](https://cloud.githubusercontent.com/assets/23504285/21589072/5b5849f6-d107-11e6-8fea-22acb85dabfc.png)

**Comment by karthmoh** [comment]
Can you set the value of the profile option - 	XXAS: Style Sheet similar to mhamza and retest the issue.

**Comment by asinghmdcbms** [comment]
After setting profiles (XXAS: Branding Favicon,XXAS: Branding Image,XXAS: Style Sheet) for MDC Advanced Self-Service things started working fine.

The default login page for HALAMMARI was 'MDC Advanced Self-Service  - > EmployeeCenter HTML5'

While for Mostafa was 'MDC Employee Self-Service  - > EmployeeCenter HTML5'

![image](https://cloud.githubusercontent.com/assets/23504285/21589740/57c0ea94-d10e-11e6-9107-4506d65a72d6.png)


Kindly note, in production above profiles need to be set at 'MDC Advanced Self-Service' responsibility level.

Kindly take a note of this in MD120

**Comment by asinghmdcbms** [comment]
Please close this issue once above has been noted as part of MD120

**Comment by karthmoh** [comment]
Thanks @asinghmdcbms made a note. Closing this issue.
