### ISSUE TITLE
Absence chart on home page not appearing

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#45]
Absence chart on home page not appearing

![image](https://cloud.githubusercontent.com/assets/23504285/21589895/071331cc-d110-11e6-8ba8-3e985e206599.png)

**Comment by SowjanyaDudipalla** [comment]
Absence chart is appearing now.


![chart1 1](https://cloud.githubusercontent.com/assets/21194907/21634651/c3311986-d27e-11e6-801e-16c47ce4e240.PNG)
