### ISSUE TITLE
Placement of blocks on home page

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#47]
We want the placement of blocks on home page to be similar to below -

![image](https://cloud.githubusercontent.com/assets/23504285/21593306/253fbe94-d12f-11e6-89e1-a34c4a2782db.png)

---------------------------------------------------------------------
Also, please let us know if the below can be achieved -

 In iPhone/Note7, the ordering should be as  follows (we don't want  leave balance graph in mobile phone on home page)
 1) Payslip right at top
 2) Then quicklinks (can we make quiklinks smaller, they seem to be consuming a lot of space both on desktop as well as mobile )
 3) Then worklist

Please note that intention of above requirement is -
 
When a user opens EmployeeCenter app on my iPhone 6/Samsung Edge(most commonly used models in Mubadala), without dragging down or sideways, user should be able to see items 1,2,3 easily.

**Comment by JaganMohan27** [comment]
Please verify once in Mobile.
![47](https://cloud.githubusercontent.com/assets/13519201/21638998/d81a86d8-d293-11e6-8bde-24d7cdbc3481.PNG)

**Comment by asinghmdcbms** [comment]
Looks fine on mobile now.

A couple of new requests from business  -

1) Move 'Getting Started' and 'Your Opinion Counts' blocks from 'Welcome' to the 'Home' page, right at the bottom.  'Your Opinion Counts' block must be the last block when viewed in mobile device.

2) After step (1), 'Welcome' page will be left with only one block. Move the 'Welcome' page right at the bottom, below 'Other Requests' menu. 

3) After step (2)  'Welcome ' page would be gone. In place of that place the 'At a Glance page' and have the page label named as 'Home'

Let me know if you have any queries.

**Comment by JaganMohan27** [comment]
Please verify once.
![47](https://cloud.githubusercontent.com/assets/13519201/21671036/b91243d8-d33e-11e6-99b9-11861bafd75d.PNG)
![47_1](https://cloud.githubusercontent.com/assets/13519201/21671037/b917f008-d33e-11e6-8020-97fbf6f768c6.PNG)
