### ISSUE TITLE
Modified image Mubadala_1200X400.jpg on crp2

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#48]
hi ,

I modified image Mubadala_1200X400.jpg placed at location $OA_MEDIA/xxas/  on crp2

Kindly add the new image to your configuration patch.

![mubadala_1200x400](https://cloud.githubusercontent.com/assets/23504285/21600226/3eb50376-d192-11e6-87d8-6a11dd5a4585.jpg)

**Comment by JaganMohan27** [comment]
Source control the image and updated manifest.
