### ISSUE TITLE
Getting error when launching native app on of the iPad devices

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#49]
![image](https://cloud.githubusercontent.com/assets/23504285/21600388/de6763f8-d194-11e6-9b64-ecb3d2220b14.png)

**Comment by hgajula-applaud** [comment]
Once you press Ok ,does the app works ?

**Comment by asinghmdcbms** [comment]
Yes it works fine after pressing OK.  Please note on my other iPad I didn't get any issue at all. 

Shortly I will be posting you steps to configure app on iOS and android in Mubadala MDM, so that it may tried by yourself as well.

**Comment by hgajula-applaud** [comment]
If it works on one device then it should work on other devices too. Can you check on other devices apart from the iPad where it was failing ?

**Comment by asinghmdcbms** [comment]
You  are right Hari, logically it should work. But I got the error, hence want to be double sure that when we go live it should not fail for some users. Basic wanted to identify the root cause of issue I faced as per screenshot.

**Comment by asinghmdcbms** [comment]
We will re-open this issue in case we encounter this issue on any other device

**Comment by asinghmdcbms** [comment]
Again got this error on one of our users device( iPhone7)

Got earlier on my iPad Air2.

**Comment by karthmoh** [comment]
As it is mentioned in #6 that no error is occurring closing this issue. Kindly reopen if the issue still persists.
