### ISSUE TITLE
Difference in Profile->Overview region between production and crp2 instance 

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#51]
Difference in Profile->Overview region between production and crp2 instance 

![image](https://cloud.githubusercontent.com/assets/23504285/21618903/afde1564-d206-11e6-8eb0-c13c168cf877.png)

**Comment by JaganMohan27** [comment]
Provided grant to Contact details and Employee Details.
![51](https://cloud.githubusercontent.com/assets/13519201/21634703/2ec1eb94-d27f-11e6-9f62-5af3c91a2500.PNG)
