### ISSUE TITLE
Date selector is glitchy

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#52]
We have got feedback from a lot of our business users that date selector is very glitchy in html5 release . And I do feel the same. Since date selection is quite common in a lot of our important  business processes, can this fixed on priority.

![image](https://cloud.githubusercontent.com/assets/23504285/21619249/4f4339ee-d208-11e6-8fb7-290cc9d03a0e.png)

**Comment by hgajula-applaud** [comment]
Please raise an SR on this as this is more related to Software .

**Comment by asinghmdcbms** [comment]
Raised below SR -

Request #87787 Applaud html5 date selector is very glitchy
