### ISSUE TITLE
'Request More Information' in notification issue

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#56]
![image](https://cloud.githubusercontent.com/assets/23504285/21633190/611d31c0-d266-11e6-8f93-ebe99855d5ed.png)

**Comment by hgajula-applaud** [comment]
We need to understand what you are looking for here and this is out of SOW request.
Suggest you to raise a SR .

**Comment by asinghmdcbms** [comment]
Lets close this after we have discussed on this during our meeting

**Comment by karthmoh** [comment]
Kindly raise an SR for this.
