### ISSUE TITLE
Getting error after login

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#57]
![image](https://cloud.githubusercontent.com/assets/23504285/21633644/6bc451f4-d26a-11e6-9ca6-ca1bf663a2e6.png)

**Comment by karthmoh** [comment]
Hi @asinghmdcbms, This error is due to the work in progress for the Absence Chart item #45 . I believe once that item is closed you should not be encountering this error.

Kindly review now.
Thanks.
