### ISSUE TITLE
Profile XXAS: Color Theme    

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#61]
Profile 'XXAS: Color Theme' is set to 'XXAS: COLOUR THEME MUBADALA' on crp2. What is its intended functionality ?

![image](https://cloud.githubusercontent.com/assets/23504285/21749760/22fe4ecc-d5bf-11e6-80a4-2dc1221c47d7.png)

**Comment by SowjanyaDudipalla** [comment]
This value will be useful for setting branding.

For more information please check the below link  : 
http://support.applaudsolutions.com/hc/en-us/articles/215976917-How-to-change-the-colour-scheme-in-Applaud

**Comment by duncancasemore** [comment]
Sure, but the profile value isn't correct here.  It needs to be set to a theme Id, eg, **mubadala**.  NB: this is just an example - I don't know if this a real theme id or not.
