### ISSUE TITLE
Payslip redirection to OAF paylsip

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#64]
Until we have permanent fix for issue #50 , kindly redirect the payslip link to old OAF page.

**Comment by SowjanyaDudipalla** [comment]
Now latest payslip will be redirected to OAF payslip page as you required .
please check .

![lat_pay](https://cloud.githubusercontent.com/assets/21194907/21880317/4aebb49e-d8c4-11e6-9639-b099f919f575.PNG)
