### ISSUE TITLE
Home page UI issue

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#65]
![image](https://cloud.githubusercontent.com/assets/23504285/21850018/0e9d5b52-d822-11e6-8e91-7de0a489f826.png)

**Comment by SowjanyaDudipalla** [comment]
Removed  Employee Center Home as you required .

![ec home](https://cloud.githubusercontent.com/assets/21194907/21880719/7c7db1ae-d8c6-11e6-8b96-8f22efd7aa03.PNG)
