### ISSUE TITLE
Home page absence graph issue

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#66]
![image](https://cloud.githubusercontent.com/assets/23504285/21850198/dda3461e-d822-11e6-96eb-4e110a569b32.png)

**Comment by JaganMohan27** [comment]
Please see the Home page absence graph.
![66](https://cloud.githubusercontent.com/assets/13519201/21882434/7330783e-d8d0-11e6-98a4-bf73dc21e403.PNG)
