### ISSUE TITLE
Rename Home to EmployeeCenter Home

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#67]
![image](https://cloud.githubusercontent.com/assets/23504285/21850309/67299334-d823-11e6-9c22-c092fe4b5aca.png)

**Comment by JaganMohan27** [comment]
Renamed Home to EmployeeCenter Home.
![67](https://cloud.githubusercontent.com/assets/13519201/21879531/72e9e204-d8bf-11e6-8b98-b942e20eebc2.PNG)

**Comment by asinghmdcbms** [comment]
![image](https://cloud.githubusercontent.com/assets/23504285/21962004/65d886e0-db32-11e6-8f25-c8f775afd2c7.png)

**Comment by asinghmdcbms** [comment]
![image](https://cloud.githubusercontent.com/assets/23504285/21962018/c89e4742-db32-11e6-80ba-11dfa162f754.png)

**Comment by JaganMohan27** [comment]
This is UI know issue. Fix is available on next patch.

**Comment by asinghmdcbms** [comment]
When is the next patch getting released ?

**Comment by JaganMohan27** [comment]
Our suggestion is to reduce the text. If you are looking for a different prompt we have provided the manual step in MD120.
Please see the below screenshot.
