### ISSUE TITLE
Workaround fix for #29

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#68]
As a workaround for issue #29 , please change the label M-Power to  'M-Power Home' and make it as a  URL to advanced menu. We will try to convince business users to use it as a workaround for issue #29

![image](https://cloud.githubusercontent.com/assets/23504285/21850481/36d7c448-d824-11e6-8051-99a66b3e40a1.png)

**Comment by hgajula-applaud** [comment]
@uiguru let us know when you have the image ready.

**Comment by SowjanyaDudipalla** [comment]
Changes are made according to your requirement, M-POWER HOME button will redirect you to Advanced menu.Please check.

![ec home](https://cloud.githubusercontent.com/assets/21194907/21880333/7146d3b2-d8c4-11e6-9efe-29251057747f.PNG)

**Comment by SowjanyaDudipalla** [comment]
@asinghmdcbms 
Can you please check which is fine for you
Image 1  or 2 ?
Image 1:
![ec home](https://cloud.githubusercontent.com/assets/21194907/21880634/0476d0f0-d8c6-11e6-85cd-28bf3c6efc94.PNG)

Image 2:
![ec home1](https://cloud.githubusercontent.com/assets/21194907/21880663/2a237d8a-d8c6-11e6-924b-1180175e6883.PNG)

**Comment by asinghmdcbms** [comment]
Please make it as image 1.

**Comment by JaganMohan27** [comment]
Image 1 is done.

![68](https://cloud.githubusercontent.com/assets/13519201/21973621/fe56daf6-dbe7-11e6-83df-212bc04be1ed.PNG)
