### ISSUE TITLE
getting error on crp2

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#69]
![image](https://cloud.githubusercontent.com/assets/23504285/21974144/5b0cc38c-dbde-11e6-8d32-3d9ee7565c83.png)

**Comment by JaganMohan27** [comment]
Working for for HALBAHSI and MHAMZA users. 
![69](https://cloud.githubusercontent.com/assets/13519201/22008637/fc2e67ec-dca2-11e6-885a-f6ef5398bee5.PNG)
