### ISSUE TITLE
Home page issue after applying configuration patch on fresh instance

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#70]
We applied the latest software and configuration patch on a fresh instance and got the below home page 

![image](https://cloud.githubusercontent.com/assets/23504285/22021615/b9e12782-dcd7-11e6-8269-b3085ebc0acf.png)

We have completed all the steps as per the latest MD120

Also, I can see that grant for advert section is missing. When I try to create grant by pressing the 'Add' button, I get the below error 

![image](https://cloud.githubusercontent.com/assets/23504285/22021701/1b2dbb54-dcd8-11e6-8786-3156fb2d4701.png)

**Comment by SowjanyaDudipalla** [comment]
Can you please run the below query in fresh instance where latest patch is applied and share the output :  
  SELECT *FROM xxas_pages_v WHERE  menu_name= 'XXX_XXAS_PG_AT_A_GLANCE';

If possible can you please share "dev"  instance details.

Thanks

**Comment by asinghmdcbms** [comment]
[query_output.zip](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/713126/query_output.zip)

This is a restricted environment. We can have web conference in case you want to troubleshoot the issue

**Comment by SowjanyaDudipalla** [comment]
We are fine with web conference.
Let us know when you are free,we will plan accordingly.

**Comment by asinghmdcbms** [comment]
Currently on call with Sateesh. Once finished we can start with the call. Let me know meeting details.

**Comment by karthmoh** [comment]
Hi @asingmdcbms,

We reviewed the ldt file which delivers the configuration and it has the required grants in it.

Could you please share the log files generated while applying the patch. 
Also please provide us the output of the below query.

select * from xxas_com_applied_files where file_name = 'xxx_xxas_glance_menu_pg.ldt';

Thanks,
Karthik.

**Comment by asinghmdcbms** [comment]
![image](https://cloud.githubusercontent.com/assets/23504285/22062424/0adc2da6-dd93-11e6-93bf-a48bef6ac91a.png)

**Comment by SowjanyaDudipalla** [comment]
@asinghmdcbms 
Can you please run the below statement in dev instance: 
FNDLOAD apps/<<apps_password>> 0 Y UPLOAD $XXAS_TOP/import/xxas_full_page_loader.lct $XXAS_TOP/custom/mubadala_html5/import/xxx_xxas_glance_menu_pg.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE

**Comment by asinghmdcbms** [comment]
Below is how page getting displayed after running above command

![image](https://cloud.githubusercontent.com/assets/23504285/22104699/022e9f3c-de5a-11e6-81dd-6c4e7b2910e8.png)

**Comment by SowjanyaDudipalla** [comment]
@asinghmdcbms 
issues are:
1.Missing advert: I understood why it happened, need to change the path for the image file.
2.Missing Notifications page
       for this can you please check 
             Message :  XXX_XXAS_PG_WORKLIST_T is present in "dev"  instance or not
          and
      please check grants for Permission Set : "XXX_XXAS_BK_NOTIFICATIONS_PSET"
3.Missing Quick links 
       for this check  menu  : "XXX_XXAS_COM_ACT_QUICKLINKS" and grants for this menu.

Please check in dev instance if any specified message/menu/permission set/grants missed. 
Thanks

**Comment by asinghmdcbms** [comment]
I am available today. Lets have call , I will give you control, identify the issues and update the patch.

That will be much quicker, instead of going back and forth with queries.

Let me know time convenient to you.

**Comment by SowjanyaDudipalla** [comment]
Hi @asinghmdcbms 
That's great.
We are available now.Let us know when you are free,we will plan accordingly.

**Comment by asinghmdcbms** [comment]
Lets have it now. Share with me meeting details.

**Comment by SowjanyaDudipalla** [comment]
could you please check your mail for meeting details.

**Comment by SowjanyaDudipalla** [comment]
@asinghmdcbms
Can you please run the below statement in dev instance:
FNDLOAD <<apps_username>>/<<apps_password>> 0 Y UPLOAD  $FND_TOP/patch/115/import/afsload.lct xxx_xxas_quick_links_grant_menu.ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE


and Check "dev" instance for QUICK LINKS.



Please compile the below script and commit : 

[script_wl.txt](https://github.com/ApplaudSolutions/Mubadala-HTML5-Upgrade-/files/719237/script_wl.txt)


After compiling please share the screenshot of HOME page.

**Comment by asinghmdcbms** [comment]
Issues :
 1) Quick links missing
 2) Find Jobs coming in search window; also search not working
3) M-Power Home link not displayed as blue color bold



![image](https://cloud.githubusercontent.com/assets/23504285/22192053/17ac2562-e14a-11e6-94ba-55bb9c480469.png)

**Comment by SowjanyaDudipalla** [comment]
Hi @asinghmdcbms 
If you are available, can we go for a call today.

**Comment by asinghmdcbms** [comment]
Yes...can we have it now

**Comment by asinghmdcbms** [comment]
Let me know meeting details

**Comment by SowjanyaDudipalla** [comment]
Hi @asinghmdcbms 
Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/922643141

You can also dial in using your phone. 
United Kingdom : +44 (0) 20 3713 5010

Access Code: 922-643-141

**Comment by karthmoh** [comment]
We had a call with Amit today, and resolved the outstanding issues during the call. The issues is that the grants for Quick links and People Search was not created even though the patch delivers the ldt file. Manually uploaded the ldt files and the issues were resolved. @SowjanyaDudipalla is working on a latest patch which includes some fixes around the Hiding the title for EmployeeCenter Home and updating the correct Advert image location in the function parameter, new message for EmployeeCenter Home, update of parameter to Advert block from pLine1 to pButtonText. 

MD120 to be updated accordingly.

**Comment by SowjanyaDudipalla** [comment]
MD120 is updated with the fix for the recently reported issue. Kindly refer to the same in #8
